scripts: add command line args
lona-web-org/lona pull request #127
Opened 2021-09-22 07:19 UTC by fscherf

With these patches command line arguments can be used in Lona scripts.

``python lona_script.py --port=8081 --shell -O Foo=True``

2021-09-22 11:43 UTC, maratori requested changes
I believe parsing command line arguments is not a responsibility of `LonaApp`.
It already can receive arbitrary arguments in `app.run()`.

If I want to parse arguments I should do it outside of `LonaApp`.
We can add some helper function. For example
```py
app = LonaApp(__file__)
# setup views
app.run(**parse_command_line(port=8080))
```

2021-09-22 11:43 UTC, maratori commented on lona/app.py
> +            parse_command_line: int = True,
```suggestion
            parse_command_line: bool = True,
```

2021-09-22 11:43 UTC, maratori commented on lona/app.py
> +            settings_pre_overrides: Union[Dict, None] = None,
nit:
```suggestion
            settings_pre_overrides: Optional[Dict[str, Any]] = None,
```

2021-09-22 14:08 UTC, fscherf commented on lona/app.py
> +            settings_pre_overrides: Union[Dict, None] = None,
Fixed

2021-09-22 14:08 UTC, fscherf commented on lona/app.py
> +            parse_command_line: int = True,
Fixed

2021-09-22 14:08 UTC, fscherf commented on lona/app.py
> +            ),
fixed

2021-09-22 14:18 UTC, fscherf commented
@maratori I think it's a very useful feature that you just call ``app.run()`` and can override the port for example. If we get a bug report with a reproducing script, the first thing i do is patching ``app.run()`` to ``app.run(log_level='debug', shell=True)``. It would be nice to just run it with ``-l debug --shell`` without changing something.

If we put this functionality in it's own place, i would recommend everyone to use it, because it adds the same interface to scripts like in projects, which is especially useful if you read https://lona-web.org/end-user-documentation/debugging.html while developing. I think it makes it consistent.

Also: I like debugging infrastructure that's always in place. Not only if you set it up. I can tell every user to add ``-l debug``, but not every user to patch a line of code.

Is there a reason to split that, that i miss?

2021-09-23 14:04 UTC, maratori approved these changes
@fscherf Ok

2021-09-23 19:47 UTC, fscherf commented
@maratori Thanks for reviewing!

2021-09-23 19:49 UTC, merged

2021-09-25 09:06 UTC, themutt approved these changes